---
title: "Oct 18 Suvival Analysis"
author: "Shelly Trigg"
date: "11/12/2019"
output: html_document
---

load libraries
```{r}
library(readxl)
library(ggplot2)
```


read in data 
```{r}
fileName <- "20191018_ShellLength.xlsx"
#code from: https://stackoverflow.com/questions/12945687/read-all-worksheets-in-an-excel-workbook-into-an-r-list-with-data-frames
#define the function for reading in the excel file with multiple tabs
read_excel_allsheets <- function(fileName, tibble = FALSE) {
  sheets <- readxl::excel_sheets(fileName)
  x <- lapply(sheets, function(X) readxl::read_excel(fileName, sheet = X))
  if(!tibble) x <- lapply(x, as.data.frame)
  names(x) <- sheets
  x
}
# create R object for excel file 
sheets <- read_excel_allsheets("20191018_ShellLength.xlsx")
list2env(sheets ,.GlobalEnv)
#create data frame from excel datafile
dt <- data.frame()
for(i in 1:length(sheets)){
  dtemp <- data.frame(sheets[i])
  dtemp$Image <- names(sheets)[i]
  colnames(dtemp) <- c("Area","Mean", "Min", "Max", "Angle", "Length (inch)", "Length (cm)", "Image")
  dt <- rbind(dt, dtemp)
}

# add Silo Information 
dt$Silo <- gsub(".*_","",dt$Image)


#Read in the parental history and treatment conditions
meta_data <- read_excel("Fall2019_AmbxVar.Low_juv_MetaData.xlsx")
#change column name to match that in dt
colnames(meta_data)[1] <- "Silo"

#merge dt data with meta data
dt <- merge(dt,meta_data, by = "Silo")

#create a new column with parental history and current treatment info
dt$parental_currenttreatment <- paste(dt$Parental.history,dt$Sw.Condition,sep = "_")


#read in Steven's survival data
Oct18_counts <- read_excel("20191018_survival.xlsx")
Oct18_counts$avg.count <- as.integer(Oct18_counts$avg.count)
Oct18_counts$parental_currenttreatment <- paste(Oct18_counts$parental.history,Oct18_counts$sw.condition,sep = "_")
```

create data frame with final counts
```{r}

img_counts <- data.frame(table(dt$Silo))
colnames(img_counts) <- c("Silo", "live.animals")
img_counts <- merge(img_counts, meta_data, by = "Silo")
img_counts$parental_currenttreatment <- paste(img_counts$Parental.history,img_counts$Sw.Condition,sep = "_")


```




plot survival data from image data
```{r}
ggplot(img_counts,aes(x = parental_currenttreatment, y = live.animals, color = parental_currenttreatment)) + geom_jitter(shape = 16, size = 3, position = position_jitter(0.2)) + theme_bw()+ ggtitle("End point survival from image data") + ylab("Number animals alive") + xlab("parental.history_current.condition") + theme(legend.position = "none")
```

plot survival data from Steven's counts
```{r}
ggplot(Oct18_counts,aes(x = parental_currenttreatment, y = avg.count, color = parental_currenttreatment)) + geom_jitter(shape = 16, size = 3, position = position_jitter(0.2)) + theme_bw() + ggtitle("End point survival from Oct 18 counts") + ylab("Number animals alive") + xlab("parental.history_current.condition") + theme(legend.position = "none")

jpeg("SiloSurvCounts_vs_TreatmentGroup.jpeg", width = 8, height = 8, units = "in", res = 300)
ggplot(Oct18_counts,aes(x = parental_currenttreatment, y = avg.count, color = parental_currenttreatment)) + geom_jitter(shape = 16, size = 3, position = position_jitter(0.2)) + theme_bw() + ggtitle("End point survival from Oct 18 counts") + ylab("Number animals alive") + xlab("parental.history_current.condition") + theme(legend.position = "none")
dev.off()

```

run aov on Steven's counts

```{r}
surv_aov <- aov(avg.count ~ parental.history * sw.condition, data = Oct18_counts)
summary(surv_aov)
```

run Tukey's HSD
```{r}

TukeyHSD(surv_aov)

```